name: Cビルド

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ファイル一覧表示
        run: ls -R

      - name: GCCのバージョン確認
        run: gcc --version

      - name: Hello表示
        run: echo "GitHub Actionsが正常に動いています！"