name: Cビルド

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v4

      - name: GCCのバージョンを表示
        run: gcc --version

      - name: cppcheckをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: cppcheckで静的解析
        run: |
          cppcheck --enable=all --inconclusive --std=c99 . 2> cppcheck.txt
          cat cppcheck.txt

      - name: converter_tag.c をコンパイル
        run: gcc converter_tag.c -o converter

      - name: 成果物を保存
        uses: actions/upload-artifact@v4
        with:
          name: converter
          path: converter

      - name: プログラム実行
        run: ./converter test/input.fps output.fps

      - name: 出力を比較
        run: cmp output.fps test/expected.fps