name: Cビルド

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v4

      - name: GCCのバージョンを表示
        run: gcc --version

      - name: converter_tag.c をコンパイル
        run: gcc converter_tag.c -o converter

      - name: 成果物を保存
        uses: actions/upload-artifact@v4
        with:
          name: converter
          path: converter